package com.mobiquity.testapp.presentation.list

import kotlin.reflect.KClass

inline fun <reified T : Any> createInstance(): T {
    return createInstance(T::class)
}

@Suppress("UNUSED_PARAMETER")
fun <T : Any> createInstance(kClass: KClass<T>): T {
    return castNull()
}

/**
 * Uses a quirk in the bytecode generated by Kotlin
 * to cast null to a non-null type.
 *
 * See https://youtrack.jetbrains.com/issue/KT-8135.
 */
@Suppress("UNCHECKED_CAST")
private fun <T> castNull(): T = null as T